source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# Authentication
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.12"

# CORS
gem "rack-cors"

# Serialization
gem "active_model_serializers", "~> 0.10"

# Redis for ActionCable
gem "redis", "~> 5.0"

# JWT decoding for ActionCable
gem "jwt", "~> 2.7"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end
